import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,1,2])
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.sum(arr))
print(np.prod(arr))
print(np.std(arr))
print(np.var(arr))
print(np.percentile(arr,90))
print(np.argmax(arr))
print(np.argmin(arr))
print(np.unique(arr))
print(np.diff(arr))
print(np.cumsum(arr))
print(np.exp(arr))