import pandas as pd
df=pd.read_csv("sample_dataset.csv")
print(df)
df=df.sort_values("Marks")
print(df)
df=df.sort_values("Marks",ascending=False)
print(df)
df=df.sort_values(["Marks","Name"])
print(df)
df2=df.copy()
print(df2)
df2.reset_index(drop=True,inplace=True)
print(df2)